### ISSUE TITLE
Error 403 Forbidden for Proxy

### ISSUE THREAD

**Issue by Anishohri** [echoAlexey/selenium-examples#1]
Hi

Any help on this would be greatly appreciated.

I am trying to work with sikuli and selenium Grid. did all the configuration etc and when i run i get 403 forbidden error (complete error logs below):
io.sterodium.rmi.protocol.server.TargetServerException: Widget target-factory invocation failed (expected 200, but was 403): 

Error 403 Forbidden for Proxy

HTTP ERROR: 403

Forbidden for Proxy
RequestURI=/grid/admin/HubRequestsProxyingServlet/session/57d73f94-f7ad-499a-9c1d-45992494af54/SikuliExtensionServlet/target-factory

Powered by Jetty://

at io.sterodium.rmi.protocol.client.RestTransport.send(RestTransport.java:49)
at io.sterodium.rmi.protocol.client.RestClient.invoke(RestClient.java:40)
at io.sterodium.rmi.protocol.client.RemoteInvoker.invoke(RemoteInvoker.java:36)
at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.invoke(RemoteObjectMethodInterceptor.java:69)
at io.sterodium.rmi.protocol.client.RemoteObjectMethodInterceptor.intercept(RemoteObjectMethodInterceptor.java:51)
at io.sterodium.extensions.node.rmi.TargetFactory$$EnhancerByCGLIB$$3278f426.createImageTarget(<generated>)
at com.newdemo.test.paam.sikuliremote.searchGoogleForSikuliLogo(sikuliremote.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
This is the my class:
package com.newdemo.test.paam;

import com.codeborne.selenide.WebDriverRunner;

import io.sterodium.extensions.client.SikuliExtensionClient;
import io.sterodium.extensions.node.rmi.TargetFactory;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.Platform;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.sikuli.api.DesktopScreenRegion;
import org.sikuli.api.ImageTarget;
import org.sikuli.api.ScreenRegion;
import org.sikuli.api.robot.Mouse;

import java.net.MalformedURLException;
import java.net.URL;

import static com.codeborne.selenide.Selenide.open;

public class sikuliremote {

private static final String GOOGLE_IMAGES_BUNDLE = "/Users/anish_ohri/Desktop/image.png";
private static final String GOOGLE_IMAGES_URL = "https://images.google.com/";
private static final String SIKULI_LOGO_SEARCH = "sikuli logo";

private static final String SEARCH_FIELD_IMG = "search_field.png";
private static final String SEARCH_BUTTON_IMG = "search_button.png";
private static final String SIKULI_LOGO_IMG = "sikuli_logo.png";

@Before
public void setUp() throws MalformedURLException {
    DesiredCapabilities desiredCapabilities = firefoxWithSikuli();
    URL url = new URL(String.format("http://%s:%d/wd/hub", GridSettings.HOST, GridSettings.PORT));

    RemoteWebDriver remoteWebDriver = new RemoteWebDriver(url, desiredCapabilities);
    WebDriverRunner.setWebDriver(remoteWebDriver);
}

@After
public void tearDown() {
    WebDriverRunner.closeWebDriver();
}

private DesiredCapabilities firefoxWithSikuli() {
    DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.setBrowserName("firefox");
    desiredCapabilities.setPlatform(Platform.ANY);
    desiredCapabilities.setCapability("sikuliExtension", true);
    return desiredCapabilities;
}

@Test
public void searchGoogleForSikuliLogo() throws InterruptedException {
    open("http://google.com");

    String sessionId = getSessionId();
    SikuliExtensionClient sikuliExtensionClient = new SikuliExtensionClient(GridSettings.HOST, GridSettings.PORT, sessionId);
    TargetFactory targetFactory = sikuliExtensionClient.getTargetFactory();
    ImageTarget imageTarget = targetFactory.createImageTarget("/Users/anish_ohri/Desktop/image.png");

    DesktopScreenRegion desktop = sikuliExtensionClient.getDesktop();
    ScreenRegion screenRegion = desktop.find(imageTarget);

    Mouse mouse = sikuliExtensionClient.getMouse();
    mouse.click(screenRegion.getCenter());

 //   SikuliExtensionClient sikuliExtensionClient = new SikuliExtensionClient(HOST, PORT, sessionId);
   // sikuliExtensionClient.uploadResourceBundle(GOOGLE_IMAGES_BUNDLE);
    //SikuliHelper sikuliHelper = new SikuliHelper(sikuliExtensionClient);

}

private String getSessionId() {
    return ((RemoteWebDriver) WebDriverRunner.getWebDriver()).getSessionId().toString();
}
}

**Comment by echoAlexey** [comment]
duplicate, https://github.com/sterodium/selenium-grid-extensions/issues/43#issuecomment-203506340
